In [1]:
nums = [3,5,7,8,12]
cubes=[]
for num in nums:
    cubes.append(num ** 3)
    print(cubes)

[27]
[27, 125]
[27, 125, 343]
[27, 125, 343, 512]
[27, 125, 343, 512, 1728]


In [5]:
my_dict = {}

# Add key-value pairs
my_dict['parrot'] = 2
my_dict['goat'] = 4
my_dict['spider'] = 8
my_dict['crab'] = 10

# Print the dictionary
print(my_dict)

{'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}


In [6]:
my_dict = {
    'parrot': 2,
    'goat': 4,
    'spider': 8,
    'crab': 10
}


total_legs = 0

for animal, legs in my_dict.items():
    print(f"{animal}: {legs} legs")
    total_legs += legs


print(f"Total legs: {total_legs}")

parrot: 2 legs
goat: 4 legs
spider: 8 legs
crab: 10 legs
Total legs: 24


In [8]:
A = (3, 9, 4, [5, 6])

# Change the value from 5 to 8 in the list
A[3][0] = 8

# Print the modified tuple
print(A)


(3, 9, 4, [8, 6])


In [9]:
B = ('a', 'p', 'p', 'l', 'e')

# Counting the occurrences of 'p' in the tuple
count_p = B.count('p')

# Printing the result
print(count_p)

2


In [10]:
B = ('a', 'p', 'p', 'l', 'e')

# Finding the index of 'l' in the tuple
index_l = B.index('l')

# Printing the result
print(index_l)

3


In [14]:
def Compute(distance, time):
    if time == 0:
        return "Time cannot be zero."
    velocity = distance / time
    return velocity


In [13]:
# List of even numbers up to 12
even_num = [2, 4, 6, 8, 10, 12]

# Function to calculate the product of all elements in the list
def mult(numbers):
    product = 1
    for num in numbers:
        product *= num
    return product

# Calculate the product of all elements in even_num
result = mult(even_num)
print(result)


46080


In [15]:
import pandas as pd
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

# Print the first two rows of the DataFrame
print(df.head(2))


   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [16]:
import pandas as pd

# Create the DataFrame
data = {
    'C1': [1, 2, 3, 5],
    'C2': [6, 7, 5, 4],
    'C3': [7, 9, 8, 6],
    'C4': [7, 5, 2, 8]
}

df = pd.DataFrame(data)

# Print the second column (C2)
print("Second column (C2):")
print(df['C2'])

Second column (C2):
0    6
1    7
2    5
3    4
Name: C2, dtype: int64


In [17]:
import pandas as pd

# Create the DataFrame
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

# Print the original DataFrame
print("Original DataFrame:")
print(df)

# Rename the third column 'C3' to 'B3'
df.rename(columns={'C3': 'B3'}, inplace=True)

# Print the DataFrame with the updated column name
print("\nDataFrame with renamed column:")
print(df)

Original DataFrame:
   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8

DataFrame with renamed column:
   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [18]:
import pandas as pd

# Create the DataFrame
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

# Add the new column 'Sum' that contains the sum of each row
df['Sum'] = df.sum(axis=1)

print(df)

   C1  C2  C3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [19]:
import pandas as pd

# Define the data for the DataFrame
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Print the complete DataFrame
print(df)

   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [20]:
import pandas as pd

# Create the DataFrame
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

# Print the bottom 2 records of the DataFrame
print(df.tail(2))


   C1  C2  C3  C4
3   5   4   6   8
4   5   8   5   8


In [21]:
import pandas as pd

# Define the data for the DataFrame
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Print the DataFrame
print("DataFrame:")
print(df)

DataFrame:
   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [22]:
print("\nShape of the DataFrame (rows x columns):")
print(df.shape)
import pandas as pd

# Create the DataFrame
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

# Check for missing values
null_values = df.isnull()
print("Null Values in DataFrame:")
print(null_values)


Shape of the DataFrame (rows x columns):
(5, 4)
Null Values in DataFrame:
      C1     C2     C3     C4
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False


In [23]:
# Drop rows with missing values
df_cleaned = df.dropna()

print("\nDataFrame after dropna():")
print(df_cleaned)


DataFrame after dropna():
   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [24]:
import numpy as np

# Define the matrix A
A = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

# Convert matrix A into a NumPy array
A_np = np.array(A)

# Define the array z
z = np.array([1, 0, 1])

# Display the NumPy array A
print(A_np)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
import numpy as np

# Define the array A
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Use slicing to extract the first 2 rows and columns 1 and 2
b = A[:2, 1:3]  # Rows 0 and 1, Columns 1 and 2

print(b)


[[2 3]
 [6 7]]


In [26]:
import numpy as np

# Define matrix A
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Create an empty matrix C with the same shape as A
C = np.empty_like(A)

print(C)


[[95498278709051              0              0              0]
 [             0              0              0              0]
 [             0              0              0              0]]


In [27]:
import numpy as np

# Define the matrix A
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Define the vector z
z = np.array([1, 0, 1])

# Initialize the matrix C with the same shape as A
C = np.empty_like(A)

# Add z to each column of A using an explicit loop
for i in range(A.shape[1]):
    C[:, i] = A[:, i] + z

# Print the resulting matrix C
print("Matrix C:")
print(C)

# Create the arrays X, Y, and v
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])

# Print X, Y, and v
print("\nArray X:")
print(X)

print("\nArray Y:")
print(Y)

print("\nVector v:")
print(v)


Matrix C:
[[ 2  3  4  5]
 [ 5  6  7  8]
 [10 11 12 13]]

Array X:
[[1 2]
 [3 4]]

Array Y:
[[5 6]
 [7 8]]

Vector v:
[ 9 10]


In [28]:
import numpy as np

# Define matrix A
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Define vector z
z = np.array([1, 0, 1])

# Broadcasting to add z to each row of A
X = A + z[:, np.newaxis]  # Add z to each row of A

# Assuming Y is some other matrix of the same shape as X, let's create Y for demonstration
Y = np.array([[1, 1, 1, 1],
              [1, 1, 1, 1],
              [1, 1, 1, 1]])

# Add matrices X and Y
result = X + Y

# Print the result
print(result)


[[ 3  4  5  6]
 [ 6  7  8  9]
 [11 12 13 14]]


In [29]:
import numpy as np

# Define matrix A and vector z
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
z = np.array([1, 0, 1, 0])  # Note: `z` should be of the correct size for matrix multiplication

# Perform matrix multiplication
result = np.dot(A, z)

# Print the result
print(result)


[ 4 12 20]


In [30]:
import numpy as np

# Define matrix A and vector z
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
z = np.array([1, 0, 1, 1])

# Element-wise multiplication of A and z
Y = A * z

# Compute element-wise square root of matrix Y
sqrt_Y = np.sqrt(Y)

# Print the result
print(sqrt_Y)


[[1.         0.         1.73205081 2.        ]
 [2.23606798 0.         2.64575131 2.82842712]
 [3.         0.         3.31662479 3.46410162]]


In [33]:

import numpy as np

# Define the 2D array A
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Compute the sum of each column
column_sums = np.sum(A, axis=0)

# Print the result
print(column_sums)



[15 18 21 24]
